# logging configs
log:
  dir: /tmp/recipe
logging.file: ${log.dir}/recipe.log
logging:
  file:
    max-size: 100MB
    max-history: 30
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n %clr(%ex){red}%nopex%n'
#  level:
#    org.springframework.*: ERROR
#    org.hibernate.*: ERROR
#    guru.springframework: DEBUG